baseURL: /
title: 🔒 Django access control
enableRobotsTXT: true
theme:
  - docsy
enableGitInfo: true
contentDir: content
defaultContentLanguage: en

pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsUseClassic: false
pygmentsStyle: tango

imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango
outputs:
  section:
    - HTML
    - print
params:
  #copyright:
  # privacy_policy: 'https://policies.google.com/privacy'
  # version_menu: Releases
  # archived_version: false
  version: '1.0'
  url_latest_version: 'https://github.com/django-access-control/django-access-control'
  github_repo: 'https://github.com/django-access-control/docs'
  github_project_repo: 'https://github.com/django-access-control/django-access-control'
  #gcs_engine_id: d72aa9b2712488cc3
  #algolia_docsearch: false
  offlineSearch: true
  prism_syntax_highlighting: false
  ui:
    sidebar_menu_compact: false
    breadcrumb_disable: false
    sidebar_search_disable: false
    navbar_logo: false
    footer_about_disable: true
    readingtime:
      enable: false
#  links:
#    user:
#      - name: User mailing list
#        url: 'https://example.org/mail'
#        icon: fa fa-envelope
#        desc: Discussion and help from your fellow users
#    developer:
#      - name: GitHub
#        url: 'https://github.com/google/docsy'
#        icon: fab fa-github
#        desc: Development takes place here!
