baseURL: /
title: Django access control
enableRobotsTXT: true
theme:
  - docsy
enableGitInfo: true
contentDir: content
defaultContentLanguage: en

pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsUseClassic: false
pygmentsStyle: tango
permalinks:
  blog: '/:section/:year/:month/:day/:slug/'
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango
outputs:
  section:
    - HTML
    - print
params:
  copyright: The Docsy Authors
  privacy_policy: 'https://policies.google.com/privacy'
  version_menu: Releases
  archived_version: false
  version: '0.0'
  url_latest_version: 'https://example.com'
  github_repo: 'https://github.com/google/docsy-example'
  github_project_repo: 'https://github.com/google/docsy'
  gcs_engine_id: d72aa9b2712488cc3
  algolia_docsearch: false
  offlineSearch: false
  prism_syntax_highlighting: false
  ui:
    sidebar_menu_compact: false
    breadcrumb_disable: false
    sidebar_search_disable: false
    navbar_logo: true
    footer_about_disable: false
    readingtime:
      enable: false
  links:
    user:
      - name: User mailing list
        url: 'https://example.org/mail'
        icon: fa fa-envelope
        desc: Discussion and help from your fellow users
      - name: Twitter
        url: 'https://example.org/twitter'
        icon: fab fa-twitter
        desc: Follow us on Twitter to get the latest news!
      - name: Stack Overflow
        url: 'https://example.org/stack'
        icon: fab fa-stack-overflow
        desc: Practical questions and curated answers
    developer:
      - name: GitHub
        url: 'https://github.com/google/docsy'
        icon: fab fa-github
        desc: Development takes place here!
      - name: Slack
        url: 'https://example.org/slack'
        icon: fab fa-slack
        desc: Chat with other project developers
      - name: Developer mailing list
        url: 'https://example.org/mail'
        icon: fa fa-envelope
        desc: Discuss development issues around the project
